FROM eclipse-temurin:17-jre-alpine

WORKDIR /src

COPY target/*.jar app.jar

EXPOSE 8080

# RUN ./mvnw clean package -DskipTests

# Command to run the aplication
ENTRYPOINT ["java", "-jar", "app.jar"]
